- name: Copy cms.conf file to home directory
  become: yes
  template:
    src: cms.toml.j2
    dest: "/home/cmsuser/cms/etc/cms.toml"
    owner: cmsuser
    group: cmsuser
    mode: "0660"
  notify: Restart CMS
  tags: config

- name: Copy cms.ranking.conf file to home directory
  become: yes
  template:
    src: cms_ranking.toml.j2
    dest: "/home/cmsuser/cms/etc/cms_ranking.toml"
    owner: cmsuser
    group: cmsuser
    mode: "0640"
  when: '"cms_ranking" in services'
  notify: Restart CMS ranking service
  tags: config
