- name: Download isolate signing key
  become: yes
  get_url:
    url: https://www.ucw.cz/isolate/debian/signing-key.asc
    dest: /etc/apt/keyrings/isolate.asc
    mode: "0644"

- name: Add isolate APT repository
  become: yes
  copy:
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/isolate.asc] http://www.ucw.cz/isolate/debian/ bookworm-isolate main\n"
    dest: /etc/apt/sources.list.d/isolate.list
    mode: "0644"

- name: Update APT cache
  become: yes
  apt:
    update_cache: yes

- name: Install isolate package
  become: yes
  apt:
    name: isolate
    state: present

- name: Patch isolate config to use correct cgroup root
  become: yes
  lineinfile:
    path: /etc/isolate
    regexp: "^cg_root"
    line: "cg_root = /sys/fs/cgroup"
    state: present

- name: Allow the {{ isolate_group }} group to run isolate
  become: yes
  file:
    path: /usr/bin/isolate
    owner: root
    group: "{{ isolate_group }}"
    mode: '04750'
